platform :ios, '9.0'

target 'TreebearManager' do #工程名称
    pod 'AFNetworking', '~> 3.1.0'
    pod 'SDWebImage', '~> 4.1.0'
    pod 'FMDB', '~> 2.7.2'
    pod 'Masonry'
    pod 'MJExtension', '~> 3.0.13'
    pod 'JSONModel'
    pod 'MJRefresh', '~> 3.1.12'
    pod 'SAMKeychain'
    pod 'MBProgressHUD', '~> 1.0.0'
    pod 'SVProgressHUD','2.0.3'
    pod 'MarqueeLabel', '~> 2.2.0'
    pod 'Aspects', '~> 1.4.1'
    pod 'DZNEmptyDataSet'
    pod 'SDCycleScrollView'
    pod 'YYKit'
    pod 'TZImagePickerController'
    pod 'CocoaAsyncSocket'
    pod 'KeyboardToolBar'
    pod 'RKNotificationHub'
end
